### ISSUE TITLE
java.lang.SecurityException: Package dev.fingertips.s20refreshrate has not requested permission 

### ISSUE THREAD

**Issue by override182** [brericha/S20-Refresh-Rate#21]
Any idea why im getting this error. I've tried to install apk, not run then trigger ADB, and ive also tried installing then run APK then configure then lastly run ADB. Both returning same error in ADB.

Previous version before 1.0 didn't return the error however I did not test further since those are older versions.

I'm on exynos s20+ 

'

C:\Android\platform-tools>adb shell pm grant dev.fingertips.s20refreshrate android.permission.WRITE_SECURE_SETTINGS
Security exception: Package dev.fingertips.s20refreshrate has not requested permission android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Package dev.fingertips.s20refreshrate has not requested permission android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:433)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2932)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2896)
        at com.android.server.pm.permission.PermissionManagerService.access$1200(PermissionManagerService.java:157)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3966)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6980)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26995)
        at android.os.Binder.shellCommand(Binder.java:916)
        at android.os.Binder.onTransact(Binder.java:790)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5433)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5155)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
'

**Comment by brericha** [comment]
Version 1.0.0 does not use the write secure settings permission. It does not need the adb command.
